# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: ArtifactoryGradle@1
  inputs:
    gradleBuildFile: 'build.gradle'
    tasks: 'artifactoryPublish'
    artifactoryResolverService: 'hts2-art'
    sourceRepo: 'libs-release'
    artifactoryDeployerService: 'hts2-xary'
    targetRepo: 'libs-release-local'
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'hts2-art'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
- task: ArtifactoryXrayScan@1
  inputs:
    artifactoryService: 'hts2-xary'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    allowFailBuild: true